VELOCITY_THRESHOLD = 3
VELOCITY_WINDOW_HOURS = 4

INCOME_RATIO_THRESHOLD = 0.5

GEO_ANOMALY_THRESHOLD = 3
GEO_ANOMALY_WINDOW_HOURS = 48

HIGH_RISK_CATEGORIES = ["gambling", "crypto", "cash"]
HIGH_RISK_THRESHOLD = 0.3

UNUSUAL_HOURS_START = 0
UNUSUAL_HOURS_END = 5
UNUSUAL_HOURS_THRESHOLD = 0.5
